name: Build on aarch64-Linux-gnu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
    steps:
    - name: Install aarch64-Linux-gnu toolchain
      run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Clone code
      uses: actions/checkout@v2

    - name: Build code
      run: make

    - name: dump hexdump to README.md
      run: python3 tools/hexdump.py
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update readme hexdump
        file_pattern: '*.md'